# Generated by Django 6.0.6 on 2026-06-26 11:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TabelBuku',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul', models.CharField(max_length=255)),
                ('pengarang', models.CharField(max_length=255)),
                ('kategori', models.CharField(max_length=100)),
                ('penerbit', models.CharField(max_length=255)),
                ('tahun_terbit', models.CharField(blank=True, max_length=4, null=True)),
                ('rak', models.CharField(blank=True, max_length=50, null=True)),
                ('stok', models.IntegerField(default=0)),
                ('deskripsi', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tabel_buku',
            },
        ),
        migrations.CreateModel(
            name='TabelSiswa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=255)),
                ('kelas', models.CharField(max_length=50)),
                ('nis', models.CharField(max_length=50, unique=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'tabel_siswa',
            },
        ),
        migrations.CreateModel(
            name='TabelPeminjaman',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal_pinjam', models.DateField()),
                ('jatuh_tempo', models.DateField()),
                ('keperluan', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Dipinjam', 'Dipinjam'), ('Dikembalikan', 'Dikembalikan'), ('Terlambat', 'Terlambat')], default='Dipinjam', max_length=50)),
                ('buku', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='perpustakaan.tabelbuku')),
                ('siswa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='perpustakaan.tabelsiswa')),
            ],
            options={
                'db_table': 'tabel_peminjaman',
            },
        ),
    ]
