# Generated by Django Manual - Mengikuti Skema Database Asli
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        # 1. TABEL BUKU
        migrations.CreateModel(
            name='Buku',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul', models.CharField(max_length=255)),
                ('pengarang', models.CharField(max_length=255)),
                ('kategori', models.CharField(max_length=100)),
                ('penerbit', models.CharField(max_length=255)),
                ('tahun_terbit', models.IntegerField()),
                ('rak', models.CharField(max_length=50)),
                ('stok', models.IntegerField()),
                ('deskripsi', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tabel_buku',  # Menyesuaikan nama tabel asli kamu
            },
        ),

        # 2. TABEL SISWA
        migrations.CreateModel(
            name='Siswa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=255)),
                ('kelas', models.CharField(max_length=100)),
                ('nis', models.CharField(max_length=50, unique=True)), # Sesuai UNIQUE CONSTRAINT (nis)
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'tabel_siswa', # Menyesuaikan nama tabel asli kamu
            },
        ),

        # 3. TABEL PEMINJAMAN
        migrations.CreateModel(
            name='Peminjaman',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal_pinjam', models.DateField()),
                ('jatuh_tempo', models.DateField()),
                ('keperluan', models.TextField(blank=True, null=True)),
                ('status', models.CharField(max_length=50)),
                # Relasi Foreign Key dengan aturan ON DELETE CASCADE sesuai skema kamu
                ('buku', models.ForeignKey(db_column='buku_id', on_delete=django.db.models.deletion.CASCADE, to='perpustakaan.buku')),
                ('siswa', models.ForeignKey(db_column='siswa_id', on_delete=django.db.models.deletion.CASCADE, to='perpustakaan.siswa')),
            ],
            options={
                'db_table': 'tabel_peminjaman', # Menyesuaikan nama tabel asli kamu
            },
        ),
    ]