# Generated by Django 6.0.6 on 2026-06-18 07:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('perpustakaan', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='peminjaman',
            name='buku',
        ),
        migrations.RemoveField(
            model_name='peminjaman',
            name='siswa',
        ),
        migrations.DeleteModel(
            name='Buku',
        ),
        migrations.DeleteModel(
            name='Peminjaman',
        ),
        migrations.DeleteModel(
            name='Siswa',
        ),
    ]
